apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-service-pod
  template:
    metadata:
      labels:
        app: consumer-service-pod
    spec:
      containers:
        - image: gcr.io/sab-ors-poc-sbx-01-9096/consumer-service:latest
          name: consumer-service
            